### PR TITLE
Add typings

### LINKED ISSUE #36: Is typings available for this module?
I am not able to find an typing for the module. For now I used a declaration file. But if it is available please let me know.

### PR DESCRIPTION
**Pull request by AlexZeitler**
Will resolve #36

### CODE REVIEW

**Comment by MichielDeMey** [comment]
Hi @AlexZeitler 👋 
Can you just make sure that the files pass the [standard](https://standardjs.com/) linting rules?

**Comment by AlexZeitler** [comment]
@MichielDeMey I had to add several `devDependencies` to make linting for `standard` with TypeScript work. Should I push these as well for future typings contributors?
I could add another `script` in `package.json` named `lint-ts` as well.

**Comment by MichielDeMey** [comment]
Hi Alex, no need to push the dev dependencies specifically for TypeScript.
We might reconsider though if we have a lot of new TypeScript contributions. 👍

**Comment by AlexZeitler** [comment]
Ok, that's what is required in case you want to add it later on:

```
npm install \
  typescript \
  eslint \ 
  eslint-plugin-standard \
  eslint-plugin-promise \
  eslint-plugin-import \
  eslint-plugin-node \
  @typescript-eslint/parser \
  @typescript-eslint/eslint-plugin \
  eslint-config-standard-with-typescript \
  --save-dev
```
`lint-ts`: `./node_modules/.bin/eslint --ext .ts .`

**Comment by gillesdemey** [comment]
This looks good to merge! 👍

**Comment by gillesdemey** [comment]
Published as [`v1.3.0`](https://github.com/MichielDeMey/express-jwt-permissions/releases/tag/v1.3.0), thanks!

**Comment by AlexZeitler** [comment]
💯

Thanks as well. This package does exactly what we needed so it’ll save as a lot of work. 

Hence, this little PR was the least we could do.

**Pull request merged**
